name: ci

on:
  release:
    types: [published]
    tag:
    - v1.*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: nina1lim/randnumimg:v1.0

      -
        name: Post message on slack
        uses: bluenovaio/action-slack@main
        with:
          username: "nina1lim"
          icon_emoji: ":robot_face:"
          text:  "Name: Nina Lim Yan Qing \nMatriculation: A0144225N \nEmail: <outlook.com|e0008256@u.nus.edu> \nRepo: <https://github.com/nina1lim/CICDAssignment>\nImage name: nina1lim/cicdassignment:${{github.ref_name}}\nImage url: <https://hub.docker.com/repository/docker/nina1lim/cicdassignment|https://hub.docker.com/repository/docker/nina1lim/cicdassignment>"

          webhook_url: ${{ secrets.SLACK_WEBHOOK }}